name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        env:
          scheme: ${{ 'default' }}
        run: |
          if [ $scheme = default ]; then scheme=$(cat default); fi
          xcodebuild clean build analyze -scheme "$scheme" -project /Users/runner/work/AppleEndpointSecurityFrameworkTest/src/MyEndPoint/MyEndPoint.xcodeproj | xcpretty && exit ${PIPESTATUS[0]}
